### ISSUE TITLE
Hang at org.jboss.pull.shared.connectors.github.GithubHelper.getPullRequests(GithubHelper.java:132)

### ISSUE THREAD

**Issue by wolfc** [jboss-set/pull-request-processor#57]
See http://10.69.5.91:8380/hudson/job/Pull-Processor_jbossas-jboss-eap/352

```
"main" prio=10 tid=0x00007f6db4008800 nid=0xd571 runnable [0x00007f6dba306000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
    at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:554)
    at sun.security.ssl.InputRecord.read(InputRecord.java:509)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
    - locked <0x000000075a50b148> (a java.lang.Object)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:884)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
    - locked <0x000000075a88ff20> (a sun.security.ssl.AppInputStream)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    - locked <0x000000075ab17ef8> (a java.io.BufferedInputStream)
    at sun.net.www.MeteredStream.read(MeteredStream.java:134)
    - locked <0x000000075ab1c720> (a sun.net.www.http.KeepAliveStream)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3053)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    - locked <0x000000075ab1fb70> (a java.io.InputStreamReader)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:154)
    at java.io.BufferedReader.read1(BufferedReader.java:205)
    at java.io.BufferedReader.read(BufferedReader.java:279)
    - locked <0x000000075ab1fb70> (a java.io.InputStreamReader)
    at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:825)
    at com.google.gson.stream.JsonReader.nextString(JsonReader.java:1045)
    at com.google.gson.stream.JsonReader.nextValue(JsonReader.java:784)
    at com.google.gson.stream.JsonReader.objectValue(JsonReader.java:766)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:380)
    at com.google.gson.stream.JsonReader.advance(JsonReader.java:426)
    at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:637)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:170)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
    at com.google.gson.Gson.fromJson(Gson.java:795)
    at com.google.gson.Gson.fromJson(Gson.java:761)
    at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:422)
    at org.eclipse.egit.github.core.client.GitHubClient.getBody(GitHubClient.java:529)
    at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:736)
    at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
    at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
    at org.eclipse.egit.github.core.service.PullRequestService.getPullRequests(PullRequestService.java:152)
    at org.jboss.pull.shared.connectors.github.GithubHelper.getPullRequests(GithubHelper.java:132)
    at org.jboss.pull.shared.PullHelper.getOpenPullRequests(PullHelper.java:102)
    at org.jboss.pull.processor.processes.eap6.ProcessorEAP6.run(ProcessorEAP6.java:46)
    at org.jboss.pull.processor.Main.main(Main.java:30)
```

**Comment by soul2zimate** [comment]
Out of Date after Aphrodite refacotring.
