### ISSUE TITLE
Ensure failed operations are properly logged either in report or via whatever way

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#68]
For instance:

EVERE: Unable to retrieve Issue at https://issues.jboss.org/browse/WFCORE-1463:
org.jboss.set.aphrodite.spi.NotFoundException: Unable to retrieve issue with id: WFCORE-1463
        at org.jboss.set.aphrodite.issue.trackers.jira.JiraIssueTracker.getIssue(JiraIssueTracker.java:122)
        at org.jboss.set.aphrodite.issue.trackers.common.AbstractIssueTracker.getIssuesAssociatedWith(AbstractIssueTracker.java:111)
        at org.jboss.set.aphrodite.Aphrodite.lambda$getIssuesAssociatedWith$4(Aphrodite.java:406)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2893)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jboss.set.aphrodite.Aphrodite.getIssuesAssociatedWith(Aphrodite.java:408)
        at org.jboss.pull.processor.impl.process.SETProcessor$PullRequestProcessingTask.call(SETProcessor.java:84)
        at org.jboss.pull.processor.impl.process.SETProcessor$PullRequestProcessingTask.call(SETProcessor.java:69)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional.of(403), errorCollections=[ErrorCollection{status=403, errors={}, errorMessages=[You do not have the permission to see the specified issue.]}]}
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:328)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:315)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:113)
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.get(DelegatingPromise.java:102)
        at org.jboss.set.aphrodite.issue.trackers.jira.JiraIssueTracker.getIssue(JiraIssueTracker.java:117)
        ... 16 more
Caused by: RestClientException{statusCode=Optional.of(403), errorCollections=[ErrorCollection{status=403, errors={}, errorMessages=[You do not have the permission to see the specified issue.]}]}
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:176)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:67)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:11)
        at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:268)
        at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:158)
        at com.google.common.util.concurrent.Futures$7.run(Futures.java:1072)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:161)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:146)
        at com.google.common.util.concurrent.AbstractFuture.done(AbstractFuture.java:235)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:172)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:268)
        at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:158)
        at com.google.common.util.concurrent.Futures$7.run(Futures.java:1072)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:161)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:146)
        at com.google.common.util.concurrent.AbstractFuture.done(AbstractFuture.java:235)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:172)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:46)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192)
        ... 3 more

or

SEVERE: Unable to retrieve Issue at https://issues.jboss.org/browse/JBEAP-10917:
org.jboss.set.aphrodite.spi.NotFoundException: Unable to retrieve issue with id: JBEAP-10917
        at org.jboss.set.aphrodite.issue.trackers.jira.JiraIssueTracker.getIssue(JiraIssueTracker.java:122)
        at org.jboss.set.aphrodite.issue.trackers.common.AbstractIssueTracker.getIssuesAssociatedWith(AbstractIssueTracker.java:111)
        at org.jboss.set.aphrodite.Aphrodite.lambda$getIssuesAssociatedWith$4(Aphrodite.java:406)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2893)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jboss.set.aphrodite.Aphrodite.getIssuesAssociatedWith(Aphrodite.java:408)
        at org.jboss.pull.processor.impl.process.SETProcessor$PullRequestProcessingTask.call(SETProcessor.java:84)
        at org.jboss.pull.processor.impl.process.SETProcessor$PullRequestProcessingTask.call(SETProcessor.java:69)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional.absent(), errorCollections=[]}
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:328)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:315)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:113)
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.get(DelegatingPromise.java:102)
        at org.jboss.set.aphrodite.issue.trackers.jira.JiraIssueTracker.getIssue(JiraIssueTracker.java:117)
        ... 16 more
Caused by: RestClientException{statusCode=Optional.absent(), errorCollections=[]}
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$3.apply(AbstractAsynchronousRestClient.java:191)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$3.apply(AbstractAsynchronousRestClient.java:185)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:81)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:11)
        at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:268)
        at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:158)
        at com.google.common.util.concurrent.Futures$7.run(Futures.java:1072)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:161)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:146)
        at com.google.common.util.concurrent.AbstractFuture.done(AbstractFuture.java:235)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:172)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:268)
        at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:158)
        at com.google.common.util.concurrent.Futures$7.run(Futures.java:1072)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:161)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:146)
        at com.google.common.util.concurrent.AbstractFuture.done(AbstractFuture.java:235)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:172)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:46)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192)
        ... 3 more
Caused by: org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 0 of 
        at org.codehaus.jettison.json.JSONTokener.syntaxError(JSONTokener.java:439)
        at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:169)
        at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:266)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$1.handle(AbstractAsynchronousRestClient.java:147)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$3.apply(AbstractAsynchronousRestClient.java:189)
        ... 28 more

**Comment by soul2zimate** [comment]
It seems that this is resolved in https://github.com/jboss-set/pull-request-processor/pull/72
