### ISSUE TITLE
NPE on PullRequestWrapper

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#69]
SEVERE: failed to https://github.com/jbossas/jboss-eap7/pull/1903
java.lang.NullPointerException
	at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPatch(GitHubWrapper.java:67)
	at org.jboss.set.aphrodite.repository.services.github.GitHubRepositoryService.getPatch(GitHubRepositoryService.java:118)
	at org.jboss.set.aphrodite.repository.services.github.GitHubRepositoryService.findPatchesRelatedTo(GitHubRepositoryService.java:359)
	at org.jboss.set.aphrodite.Aphrodite.lambda$findPatchesRelatedTo$75(Aphrodite.java:600)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jboss.set.aphrodite.Aphrodite.findPatchesRelatedTo(Aphrodite.java:601)
	at org.jboss.pull.processor.impl.process.SETProcessor$PatchProcessingTask.call(SETProcessor.java:85)
	at org.jboss.pull.processor.impl.process.SETProcessor$PatchProcessingTask.call(SETProcessor.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by soul2zimate** [comment]
This because upstream pull request https://github.com/wildfly/wildfly/pull/10112 of mentioned PR has an empty body 
PR opened at https://github.com/jboss-set/aphrodite/pull/131
